apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    cloud.weave.works/launcher-info: |-
      {
        "original-request": {
          "url": "/k8s/scope.yaml?k8s-version=Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiIxMiIsIEdpdFZlcnNpb246InYxLjEyLjIiLCBHaXRDb21taXQ6IjE3Yzc3Yzc4OTgyMTgwNzNmMTRjOGQ1NzM1ODJlOGQyMzEzZGM3NDAiLCBHaXRUcmVlU3RhdGU6ImNsZWFuIiwgQnVpbGREYXRlOiIyMDE4LTEwLTMwVDIxOjM5OjE2WiIsIEdvVmVyc2lvbjoiZ28xLjExLjEiLCBDb21waWxlcjoiZ2MiLCBQbGF0Zm9ybToiZGFyd2luL2FtZDY0In0KU2VydmVyIFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiIxMCIsIEdpdFZlcnNpb246InYxLjEwLjEyIiwgR2l0Q29tbWl0OiJjNzU3YjkzY2YwMzRkNDlhZjNhM2I4ZWNlZTNiOTYzOWE3YTExZGY3IiwgR2l0VHJlZVN0YXRlOiJjbGVhbiIsIEJ1aWxkRGF0ZToiMjAxOC0xMi0xOVQxMTowNDoyOVoiLCBHb1ZlcnNpb246ImdvMS45LjMiLCBDb21waWxlcjoiZ2MiLCBQbGF0Zm9ybToibGludXgvYW1kNjQifQo=",
          "date": "Tue Mar 12 2019 09:15:36 GMT+0000 (UTC)"
        },
        "email-address": "support@weave.works"
      }
  labels:
    app: weave-scope
    name: weave-scope-cluster-agent
    weave-cloud-component: scope
    weave-scope-component: cluster-agent
  name: weave-scope-cluster-agent
  namespace: weave
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: weave-scope
        name: weave-scope-cluster-agent
        weave-cloud-component: scope
        weave-scope-component: cluster-agent
    spec:
      containers:
      - args:
        - --mode=probe
        - --probe-only
        - --probe.kubernetes.role=cluster
        - weave-scope-app.weave.svc.cluster.local:80
        command:
        - /home/weave/scope
        env: []
        image: docker.io/weaveworks/scope:1.10.2
        imagePullPolicy: IfNotPresent
        name: scope-cluster-agent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
      serviceAccountName: weave-scope
